### ISSUE TITLE
Though about fultter

### ISSUE THREAD

**Issue by System46** [mhmzdev/The_Holy_Quran_App#11]
As you may know , flutter is developped by Google , wich is openly supporting isreal and in their ToS you can read clearly that through flutter sdk  they take "analystic data" and they have right to share it with 3rd parties . With the recent leak of data of million of people trough muslim pro "https://www.vice.com/en/article/jgqm5x/us-military-location-data-xmode-locate-x", i think it's not very good to use flutter , i know that your goal was to make a useful app and i understand that, however with that being , google may do the same thing trough "analystic data" and it could be very bad for you and the end-users.

This comment was not to say that the app is bad  , i just wanted to tell you about that. I wanted myself to start making muslim prayer apps with dart & flutter , however after reading acknolwedgement and ToS , i fully understood that they can data of users at anytime wich wasn't my goal. It's very bad that today a lot of technologies are getting controlled by anti-muslim peoples. I hope you understand what i meant by writing all of this.

Thank you for reading

**Comment by shurale85** [comment]
> As you may know , flutter is developped by Google , wich is openly supporting isreal and in their ToS you can read clearly that through flutter sdk they take "analystic data" and they have right to share it with 3rd parties . With the recent leak of data of million of people trough muslim pro "https://www.vice.com/en/article/jgqm5x/us-military-location-data-xmode-locate-x", i think it's not very good to use flutter , i know that your goal was to make a useful app and i understand that, however with that being , google may do the same thing trough "analystic data" and it could be very bad for you and the end-users.
> 
> This comment was not to say that the app is bad , i just wanted to tell you about that. I wanted myself to start making muslim prayer apps with dart & flutter , however after reading acknolwedgement and ToS , i fully understood that they can data of users at anytime wich wasn't my goal. It's very bad that today a lot of technologies are getting controlled by anti-muslim peoples. I hope you understand what i meant by writing all of this.
> 
> Thank you for reading

Is there any platform that you are sure a little bit at least? I don't think "tracking" problem is all about Muslims. Anyone can be kept watch out. This is "dunja".

**Comment by emapicdev** [comment]
thank you for clarifying this point

**Comment by System46** [comment]
> > As you may know , flutter is developped by Google , wich is openly supporting isreal and in their ToS you can read clearly that through flutter sdk they take "analystic data" and they have right to share it with 3rd parties . With the recent leak of data of million of people trough muslim pro "https://www.vice.com/en/article/jgqm5x/us-military-location-data-xmode-locate-x", i think it's not very good to use flutter , i know that your goal was to make a useful app and i understand that, however with that being , google may do the same thing trough "analystic data" and it could be very bad for you and the end-users.
> > This comment was not to say that the app is bad , i just wanted to tell you about that. I wanted myself to start making muslim prayer apps with dart & flutter , however after reading acknolwedgement and ToS , i fully understood that they can data of users at anytime wich wasn't my goal. It's very bad that today a lot of technologies are getting controlled by anti-muslim peoples. I hope you understand what i meant by writing all of this.
> > Thank you for reading
> 
> Is there any platform that you are sure a little bit at least? I don't think "tracking" problem is all about Muslims. Anyone can be kept watch out. This is "dunja".

well for example i'd use a basic programming language , C++ , java , python or any with a framework where i'm sure 100% that 1- No data analytics , priviliege manual bug report 2- implement offline calculation so user doesnt need internet and app can work on all devices. For example i made a python prayer times app with Kivy 100% offline , i also made a web app with flask where i'm 100% sure that calculation is offline (no external api) and user choose the city he wants (coords are grabbed trough openstreetmap based of city name) , no automatics precise location grabber, no cookies, etc... I used python because i'm learning but it can be done in any language.

**Comment by mhmzdev** [comment]
Closing, because its not an App related issue.
Thanks
