### ISSUE TITLE
I gave this app to my non-muslim gf, and she slapped me some Ayats:

### ISSUE THREAD

**Issue by Soumyadeep98O** [mhmzdev/The_Holy_Quran_App#12]
Can anyone please tell whether the app is authentic or not? I solely believe Quran can never contain such verses, it only talks about Humanity and Brotherhood..

And these are some of the verses that she told me to check:

🔹Qu'ran 2:223 "Your wives are a place of sowing of seed for you, so come to your place of cultivation however you wish and put forth [righteousness] for yourselves. And fear Allah and know that you will meet Him. And give good tidings to the believers."
🔹Qu'ran 2:221 "And do not marry polytheistic men [to your women] until they believe. And a believing slave is better than a polytheist, even though he might please you. Those invite [you] to the Fire, but Allah invites to Paradise and to forgiveness, by His permission. And He makes clear His verses to the people that perhaps they may remember.”
🔹Qu'ran 3:151 "We will cast terror into the hearts of those who disbelieve for what they have associated with Allah of which He had not sent down [any] authority. And their refuge will be the Fire, and wretched is the residence of the wrongdoers."
🔹Qu'ran 48:29 "Muhammad is the Messenger of Allah; and those with him are forceful against the disbelievers, merciful among themselves. You see them bowing and prostrating [in prayer], seeking bounty from Allah and [His] pleasure. Their mark is on their faces from the trace of prostration. That is their description in the Torah. And their description in the Gospel is as a plant which produces its offshoots and strengthens them so they grow firm and stand upon their stalks, delighting the sowers - so that Allah may enrage by them the disbelievers. Allah has promised those who believe and do righteous deeds among them forgiveness and a great reward."
🔹Qu'ran 8:55 "Indeed, the worst of living creatures in the sight of Allah are those who have disbelieved, and they will not [ever] believe."
🔹Qu'ran 98:6 "Indeed, they who disbelieved among the People of the Scripture and the polytheists will be in the fire of Hell, abiding eternally therein. Those are the worst of creatures."
🔹Qu'ran 33:26 "And He brought down those who supported them among the People of the Scripture from their fortresses and cast terror into their hearts [so that] a party you killed, and you took captive a party."
🔹Qu'ran 3:32 "Say, "Obey Allah and the Messenger." But if they turn away - then indeed, Allah does not like the disbelievers."
🔹Qu'ran 3:28 "Let not believers take disbelievers as allies rather than believers. And whoever [of you] does that has nothing with Allah, except when taking precaution against them in prudence. And Allah warns you of Himself, and to Allah is the [final] destination."
🔹Qu'ran 4:89 "They wish you would disbelieve as they disbelieved so you would be alike. So do not take from among them allies until they emigrate for the cause of Allah. But if they turn away, then seize them and kill them wherever you find them and take not from among them any ally or helper."
🔹Qu'ran 9:5 "And when the sacred months have passed, then kill the polytheists wherever you find them and capture them and besiege them and sit in wait for them at every place of ambush. But if they should repent, establish prayer, and give zakah, let them [go] on their way. Indeed, Allah is Forgiving and Merciful."
🔹Qu'ran 9:73 "O Prophet, carry out Jihād against the disbelievers and hypocrites, and be strict with them. And their abode is Jahannam (Hell), and it is an evil terminus."
🔹Qu'ran 9:123 "O you who believe, fight those disbelievers who are near you, and let them find severity in you. Know well that Allah is with the God-fearing.
🔹Qu'ran 8:39 "And fight them until there is no fitnah and [until] the religion, all of it, is for Allah. And if they cease - then indeed, Allah is Seeing of what they do."
🔹Qu'ran 5:33 "Indeed, the penalty for those who wage war against Allah and His Messenger and strive upon earth [to cause] corruption is none but that they be killed or crucified or that their hands and feet be cut off from opposite sides or that they be exiled from the land. That is for them a disgrace in this world; and for them in the Hereafter is a great punishment"

**Comment by mhmzdev** [comment]
Asalam u alikum brother hope you are doing well.
Brother, Islam and Qur'an are clear about matters of life. And that is why Allah SWT has mentioned everything in very clear words so that instead of us (humans) trying to find the answers we have all of them in single book.

Plus, there its not just a book of humanity or brotherhood. Its a book of fear as well, fear in a sense so that we can live our lives up to our Allah's and Prophet PBUH expectations.
Lastly, it doesn't matter what you believe should be there in Qur'an or not. If it has something, you have to follow it. Our opinion doesn't matter.

JazakAllah o khairah

**Comment by Soumyadeep98O** [comment]
Yes, I know, and you also made this app very good polished, but are those verses accurately translated? Especially the verse 2:223 and 4:34 she found very offensive, Idk, are you sure your app English translation is 100% accurate?
Please respond! Mistranslations can mislead other people too...

**Comment by mhmzdev** [comment]
Yes, they are exactly up to the mark and they are clear.
You may check some tafseer (Detailed translation for better understanding)

**Comment by Soumyadeep98O** [comment]
Ok, I'll check, thanks again to your brother, for this beautiful app 💚
